repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [
      flake8-bugbear,
      flake8-builtins,
      flake8-docstrings,
      flake8-eradicate,
      flake8-expression-complexity,
      pep8-naming,
    ]
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    args: [
      --explicit-package-bases,
      --ignore-missing-imports,
      --install-types,
      --namespace-packages,
      --non-interactive,
    ]
