# Copyright Vulcan Inc. 2018-2020
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

version: 2.1
commands:
  setup:
    steps:
      - setup_remote_docker
      - checkout
      - run: pipenv install
executors:
  circleci_executor:
    docker:
      - image: circleci/python:3.6.9
jobs:
  test:
    executor: circleci_executor
    steps:
      - setup
      - run: make test
  build:
    executor: circleci_executor
    steps:
      - setup
      - run: |
          if [ "$CIRCLE_BRANCH" = "develop" ]; then
            make build beta_tag_suffix=""
          else
            make build beta_tag_suffix="-$CIRCLE_BRANCH"
          fi
      - persist_to_workspace:
          root: .
          paths:
            - dist/*.tar.gz
  publish:
    executor: circleci_executor
    steps:
      - setup
      - attach_workspace:
          at: .
      - run: touch dist/*.tar.gz
      - run: make publish pypi_repository_password="$PYPI_REPOSITORY_PASSWORD"
workflows:
  version: 2
  ci:
    jobs:
      - test: {}
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
