version: 2.1
commands:
  setup:
    steps:
      - setup_remote_docker
      - checkout
      - run: pipenv install
executors:
  circleci_executor:
    docker:
      - image: circleci/python:3.6.9
jobs:
  test:
    executor: circleci_executor
    steps:
      - setup
      - run: make test
  build:
    executor: circleci_executor
    steps:
      - setup
      - run: |
          if [ "$CIRCLE_BRANCH" = "develop" ]; then
            make build prerelease=""
          else
            make build prerelease="b$(git rev-list --count HEAD --not origin/develop)"
          fi
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
  publish:
    executor: circleci_executor
    steps:
      - setup
      - attach_workspace:
          at: .
      - run: |
          touch dist/*
          if [ "$CIRCLE_BRANCH" = "develop" ]; then
            make publish pypi_repository=pypi pypi_repository_username="__token__" pypi_repository_password="$PYPI_ORG_TOKEN"
          else
            make publish pypi_repository_username="__token__" pypi_repository_password="$TEST_PYPI_ORG_TOKEN"
          fi
workflows:
  version: 2
  ci:
    jobs:
      - test: {}
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
